In [4]:
import matplotlib
matplotlib.use('TkAgg') # 'tkAgg' if Qt not present 
import matplotlib.pyplot as plt 
import scipy as sp
import matplotlib.animation as animation
  
class Pendulum:
    def __init__(self, theta1, theta2, dt):
        self.theta1 = theta1
        self.theta2 = theta2
          
        self.p1 = 0.0
        self.p2 = 0.0
          
        self.dt = dt
          
        self.g = 9.81
        self.length = 1.0
          
        self.trajectory = [self.polar_to_cartesian()]
  
    def polar_to_cartesian(self):
        x1 =  self.length * sp.sin(self.theta1)        
        y1 = -self.length * sp.cos(self.theta1)
          
        x2 = x1 + self.length * sp.sin(self.theta2)
        y2 = y1 - self.length * sp.cos(self.theta2)
         
        print(self.theta1, self.theta2)
        return sp.array([[0.0, 0.0], [x1, y1], [x2, y2]])
      
    def evolve(self):
        theta1 = self.theta1
        theta2 = self.theta2
        p1 = self.p1
        p2 = self.p2
        g = self.g
        l = self.length
         
        expr1 = sp.cos(theta1 - theta2)
        expr2 = sp.sin(theta1 - theta2)
        expr3 = (1 + expr2**2)
        expr4 = p1 * p2 * expr2 / expr3
        expr5 = (p1**2 + 2 * p2**2 - p1 * p2 * expr1) \
        * sp.sin(2 * (theta1 - theta2)) / 2 / expr3**2
        expr6 = expr4 - expr5
         
        self.theta1 += self.dt * (p1 - p2 * expr1) / expr3
        self.theta2 += self.dt * (2 * p2 - p1 * expr1) / expr3
        self.p1 += self.dt * (-2 * g * l * sp.sin(theta1) - expr6)
        self.p2 += self.dt * (    -g * l * sp.sin(theta2) + expr6)
         
        new_position = self.polar_to_cartesian()
        self.trajectory.append(new_position)
        print(new_position)
        return new_position
 
 
class Animator:
    def __init__(self, pendulum, draw_trace=False):
        self.pendulum = pendulum
        self.draw_trace = draw_trace
        self.time = 0.0
  
        # set up the figure
        self.fig, self.ax = plt.subplots()
        self.ax.set_ylim(-2.5, 2.5)
        self.ax.set_xlim(-2.5, 2.5)
  
        # prepare a text window for the timer
        self.time_text = self.ax.text(0.05, 0.95, '', 
            horizontalalignment='left', 
            verticalalignment='top', 
            transform=self.ax.transAxes)
  
        # initialize by plotting the last position of the trajectory
        self.line, = self.ax.plot(
            self.pendulum.trajectory[-1][:, 0], 
            self.pendulum.trajectory[-1][:, 1], 
            marker='o')
          
        # trace the whole trajectory of the second pendulum mass
        if self.draw_trace:
            self.trace, = self.ax.plot(
                [a[2, 0] for a in self.pendulum.trajectory],
                [a[2, 1] for a in self.pendulum.trajectory])
     
    def advance_time_step(self):
        while True:
            self.time += self.pendulum.dt
            yield self.pendulum.evolve()
             
    def update(self, data):
        self.time_text.set_text('Elapsed time: {:6.2f} s'.format(self.time))
         
        self.line.set_ydata(data[:, 1])
        self.line.set_xdata(data[:, 0])
         
        if self.draw_trace:
            self.trace.set_xdata([a[2, 0] for a in self.pendulum.trajectory])
            self.trace.set_ydata([a[2, 1] for a in self.pendulum.trajectory])
        return self.line,
     
    def animate(self):
        self.animation = animation.FuncAnimation(self.fig, self.update,
                         self.advance_time_step, interval=25, blit=False)
 
pendulum = Pendulum(theta1=sp.pi, theta2=sp.pi - 0.01, dt=0.01)
animator = Animator(pendulum=pendulum, draw_trace=True)
animator.animate()
plt.show()

C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:23: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  x1 =  self.length * sp.sin(self.theta1)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:24: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  y1 = -self.length * sp.cos(self.theta1)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:26: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  x2 = x1 + self.length * sp.sin(self.theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:27: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  y2 = y1 - self.length * sp.cos(self.theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:30: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy

3.141592653589793 3.1315926535897933


C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:105: UserWarning: frames=<bound method Animator.advance_time_step of <__main__.Animator object at 0x0000029A87C21790>> which we can infer the length of, did not pass an explicit *save_count* and passed cache_frame_data=True.  To avoid a possibly unbounded cache, frame data caching has been disabled. To suppress this warning either pass `cache_frame_data=False` or `save_count=MAX_FRAMES`.
  self.animation = animation.FuncAnimation(self.fig, self.update,
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:40: DeprecationWarning: scipy.cos is deprecated and will be removed in SciPy 2.0.0, use numpy.cos instead
  expr1 = sp.cos(theta1 - theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:41: DeprecationWarning: scipy.sin is deprecated and will be removed in SciPy 2.0.0, use numpy.sin instead
  expr2 = sp.sin(theta1 - theta2)
C:\Users\HP\AppData\Local\Temp\ipykernel_27924\4220107901.py:45: DeprecationWarn

3.141592653589793 3.1315926535897933
[[0.00000000e+00 0.00000000e+00]
 [1.22464680e-16 1.00000000e+00]
 [9.99983333e-03 1.99995000e+00]]
3.1416024619550025 3.1315730358784974
[[ 0.00000000e+00  0.00000000e+00]
 [-9.80836521e-06  1.00000000e+00]
 [ 1.00096417e-02  1.99994980e+00]]
3.1416220786719276 3.131533800473255
[[ 0.00000000e+00  0.00000000e+00]
 [-2.94250821e-05  1.00000000e+00]
 [ 1.00292584e-02  1.99994941e+00]]
3.1416515421917035 3.1314748896896107
[[ 0.00000000e+00  0.00000000e+00]
 [-5.88886019e-05  9.99999998e-01]
 [ 1.00587027e-02  1.99994881e+00]]
3.1416909294292044 3.131396188142482
[[ 0.00000000e+00  0.00000000e+00]
 [-9.82758393e-05  9.99999995e-01]
 [ 1.00980129e-02  1.99994801e+00]]
3.1417403558935955 3.131297522559496
[[ 0.00000000e+00  0.00000000e+00]
 [-1.47702303e-04  9.99999989e-01]
 [ 1.01472469e-02  1.99994699e+00]]
3.14179997595028 3.1311786614065427
[[ 0.00000000e+00  0.00000000e+00]
 [-2.07322359e-04  9.99999979e-01]
 [ 1.02064816e-02  1.99994575e+00]]
3.14

3.2167944913302473 3.0086061125792214
[[ 0.          0.        ]
 [-0.07513098  0.99717367]
 [ 0.05746392  1.98834399]]
3.221335977534431 3.0015814070185876
[[ 0.          0.        ]
 [-0.07965884  0.99682219]
 [ 0.05989541  1.98703661]]
3.2261229906152225 2.994192601682351
[[ 0.          0.        ]
 [-0.08442971  0.99642944]
 [ 0.06243717  1.9855857 ]]
3.231165976896001 2.986424330340629
[[ 0.          0.        ]
 [-0.08945359  0.99599099]
 [ 0.06509281  1.98397652]]
3.2364754056928753 2.978261147001296
[[ 0.          0.        ]
 [-0.09474045  0.99550201]
 [ 0.06786582  1.98219304]]
3.2420616992741422 2.9696876193363053
[[ 0.          0.        ]
 [-0.10030011  0.99495723]
 [ 0.07075951  1.98021791]]
3.2479351542127604 2.9606884336267907
[[ 0.          0.        ]
 [-0.10614218  0.99435096]
 [ 0.07377693  1.97803237]]
3.2541058544541115 2.951248510723312
[[ 0.          0.        ]
 [-0.11227596  0.99367706]
 [ 0.07692087  1.97561625]]
3.2605835767747746 2.9413531320210207
[[ 0.   

4.152572281185824 1.3789731789149806
[[ 0.          0.        ]
 [-0.84735246  0.53103089]
 [ 0.13430582  0.34038197]]
4.170144053175595 1.340833167536931
[[ 0.          0.        ]
 [-0.85655232  0.51606019]
 [ 0.11712247  0.28811854]]
4.188002648459459 1.3030356221756259
[[ 0.          0.        ]
 [-0.86563136  0.50068189]
 [ 0.09873441  0.23610929]]
4.206249295822914 1.2656422303533772
[[ 0.          0.        ]
 [-0.87462252  0.48480455]
 [ 0.07917815  0.18436439]]
4.224988076461946 1.228680344338639
[[ 0.          0.        ]
 [-0.88355308  0.46833103]
 [ 0.05849382  0.13284984]]
4.244321686884421 1.1921355939842821
[[ 0.          0.        ]
 [-0.89244192  0.4511623 ]
 [ 0.03671865  0.08148589]]
4.26434790924488 1.1559472052858377
[[ 0.          0.        ]
 [-0.90129744  0.43320079]
 [ 0.0138797   0.03014893]]
4.285157376916667 1.1200067738509942
[[ 0.          0.        ]
 [-0.91011633  0.41435283]
 [-0.01001294 -0.02132352]]
4.306832999134482 1.0841608547083794
[[ 0.         

8.001257125969707 -1.279359986428518
[[ 0.          0.        ]
 [ 0.98917455  0.14674367]
 [ 0.03134239 -0.14058463]]
8.064459560596408 -1.2313288529533042
[[ 0.          0.        ]
 [ 0.97793117  0.2089273 ]
 [ 0.03499905 -0.1240577 ]]
8.126889610314842 -1.1824027601573137
[[ 0.          0.        ]
 [ 0.96299117  0.26953293]
 [ 0.03747256 -0.10916919]]
8.188509812382726 -1.1327390524804628
[[ 0.          0.        ]
 [ 0.94456532  0.32832354]
 [ 0.03898789 -0.09585744]]
8.249295203490743 -1.0824701011316817
[[ 0.          0.        ]
 [ 0.92287585  0.38509759]
 [ 0.03975651 -0.08405081]]
8.309231843932942 -1.0317063574597836
[[ 0.          0.        ]
 [ 0.89815104  0.43968705]
 [ 0.03997484 -0.07366818]]
8.368315396311147 -0.9805392862007387
[[ 0.          0.        ]
 [ 0.87062067  0.49195492]
 [ 0.03982303 -0.06461967]]
8.426549794249205 -0.929044100247009
[[ 0.          0.        ]
 [ 0.84051234  0.5417924 ]
 [ 0.03946423 -0.05680757]]
8.483946019746638 -0.8772822558706351
[[ 0

11.94746673474418 2.601608404149264
[[ 0.          0.        ]
 [-0.5801427  -0.81451485]
 [-0.06602022  0.04320193]]
12.022912259950914 2.67033357103157
[[ 0.          0.        ]
 [-0.51709917 -0.85592549]
 [-0.06309069  0.03507187]]
12.099061190438707 2.739744348190549
[[ 0.          0.        ]
 [-0.45048582 -0.89278358]
 [-0.05936574  0.02755607]]
12.175844009304235 2.8097974259697267
[[ 0.          0.        ]
 [-0.38067542 -0.92470872]
 [-0.05493456  0.02075037]]
12.25318632524157 2.880444741293927
[[ 0.          0.        ]
 [-0.30808959 -0.95135735]
 [-0.04989988  0.01473689]]
12.331009435723743 2.951634118409619
[[ 0.          0.        ]
 [-0.23319422 -0.97243018]
 [-0.04437605  0.00958189]]
12.409230962485085 3.0233099986589047
[[ 0.          0.        ]
 [-0.15649375 -0.98767895]
 [-0.03848671  0.00533381]]
12.487765550464129 3.0954142460362526
[[ 0.          0.        ]
 [-0.07852414 -0.99691221]
 [-0.03236214  0.00202175]]
12.566525619411408 3.1678870127347
[[ 0.00000000

15.892477325166567 7.272730544322051
[[ 0.          0.        ]
 [-0.18346886  0.98302552]
 [ 0.65230751  0.43395552]]
15.910588132575532 7.317795843782964
[[ 0.          0.        ]
 [-0.20124119  0.97954172]
 [ 0.65842227  0.46868094]]
15.927726922481932 7.361594289510684
[[ 0.          0.        ]
 [-0.21799897  0.975949  ]
 [ 0.66320783  0.50321802]]
15.943951507206307 7.404143468935387
[[ 0.          0.        ]
 [-0.23380395  0.97228376]
 [ 0.66671353  0.53746396]]
15.959320061374806 7.445462287873774
[[ 0.          0.        ]
 [-0.24871835  0.96857585]
 [ 0.66899167  0.5713249 ]]
15.973890735372748 7.485570606161002
[[ 0.          0.        ]
 [-0.26280425  0.96484917]
 [ 0.67009652  0.60471564]]
15.987721318434078 7.524488914881828
[[ 0.          0.        ]
 [-0.27612311  0.96112227]
 [ 0.67008349  0.6375592 ]]
16.000868950252013 7.562238054765344
[[ 0.          0.        ]
 [-0.28873537  0.95740895]
 [ 0.66900847  0.66978638]]
16.013389878834055 7.598838974466279
[[ 0.      

17.059175387612882 8.400997680191805
[[ 0.          0.        ]
 [-0.9759881   0.21782383]
 [-0.1219077   0.73796484]]
17.09716514515514 8.410945532469015
[[ 0.          0.        ]
 [-0.98355699  0.18059803]
 [-0.13469305  0.70920944]]
17.136465708069885 8.42221166641071
[[ 0.          0.        ]
 [-0.9898933   0.14181419]
 [-0.14703851  0.67995526]]
17.177124825570534 8.434921122374046
[[ 0.          0.        ]
 [-0.99483963  0.10145988]
 [-0.15889221  0.65026943]]
17.21918964646241 8.44920007654654
[[ 0.          0.        ]
 [-0.99822624  0.05953472]
 [-0.1702002   0.62022437]]
17.262705969691673 8.465174417194541
[[ 0.          0.        ]
 [-0.99987114  0.01605294]
 [-0.18090702  0.58989765]]
17.307717402970727 8.482968122366799
[[ 0.          0.        ]
 [-0.99958075 -0.02895376]
 [-0.19095655  0.55937175]]
17.35426444633053 8.50270147632343
[[ 0.          0.        ]
 [-0.99715086 -0.07543313]
 [-0.20029298  0.52873367]]
17.402383525003966 8.524489178745371
[[ 0.          0.

20.7545532890464 12.827131428857335
[[ 0.          0.        ]
 [ 0.94467268  0.32801452]
 [ 1.2024884  -0.63817959]]
20.743367766987145 12.89651233446237
[[ 0.          0.        ]
 [ 0.94828252  0.31742756]
 [ 1.27245962 -0.62856885]]
20.728848967401486 12.965793146936566
[[ 0.          0.        ]
 [ 0.95279108  0.30362667]
 [ 1.34167748 -0.61765905]]
20.71099549940755 13.035267760236346
[[ 0.          0.        ]
 [ 0.95805974  0.28656856]
 [ 1.40996248 -0.60549866]]
20.68977078699069 13.105272044074765
[[ 0.          0.        ]
 [ 0.96392583  0.266171  ]
 [ 1.47711926 -0.59210198]]
20.665094975334245 13.176192752264859
[[ 0.          0.        ]
 [ 0.9701997   0.24230673]
 [ 1.54292136 -0.57744317]]
20.63683579116784 13.248478825996267
[[ 0.          0.        ]
 [ 0.97665881  0.21479658]
 [ 1.60708972 -0.56144878]]
20.604798601687527 13.322654700360156
[[ 0.          0.        ]
 [ 0.98303794  0.18340231]
 [ 1.66926121 -0.54398867]]
20.568717069218923 13.399333638579119
[[ 0.   

17.7144519634195 15.544345792355475
[[ 0.          0.        ]
 [-0.90657805 -0.42203819]
 [-0.74368963  0.56460631]]
17.6862618243111 15.571572500200816
[[ 0.          0.        ]
 [-0.9181136  -0.39631733]
 [-0.7821453   0.59439586]]
17.658807245754 15.5999873655399
[[ 0.          0.        ]
 [-0.92864696 -0.37096472]
 [-0.82088075  0.62321154]]
17.632036779904734 15.629482658757157
[[ 0.          0.        ]
 [-0.93824393 -0.34597446]
 [-0.85984386  0.65094752]]
17.60590208153405 15.65996402465313
[[ 0.          0.        ]
 [-0.94696444 -0.32133838]
 [-0.89898362  0.67750988]]
17.580357582169228 15.691350502255892
[[ 0.          0.        ]
 [-0.95486303 -0.29704644]
 [-0.93825103  0.70281557]]
17.555360089614577 15.723574142502363
[[ 0.          0.        ]
 [-0.96198936 -0.27308695]
 [-0.9775996   0.72679121]]
17.53086835798424 15.75657937419546
[[ 0.          0.        ]
 [-0.96838855 -0.24944661]
 [-1.01698551  0.74937186]]
17.506842657040213 15.790322237617419
[[ 0.          

17.433331295413357 18.9055117728386
[[ 0.          0.        ]
 [-0.98807756 -0.15395692]
 [-0.93215091 -1.1523918 ]]
17.486011401331805 18.937330029750076
[[ 0.          0.        ]
 [-0.97860011 -0.2057713 ]
 [-0.89093866 -1.20192162]]
17.540338935932787 18.966146334211402
[[ 0.          0.        ]
 [-0.96598276 -0.25860649]
 [-0.8496563  -1.25181752]]
17.596265645850295 18.991731558423016
[[ 0.          0.        ]
 [-0.95001698 -0.31219824]
 [-0.80831985 -1.3021083 ]]
17.65375604506914 19.013859418994553
[[ 0.          0.        ]
 [-0.93050892 -0.36626923]
 [-0.76694367 -1.35280174]]
17.71279084987575 19.032307007943263
[[ 0.          0.        ]
 [-0.90727786 -0.42053168]
 [-0.72554232 -1.40387912]]
17.77337041911745 19.046854777625438
[[ 0.          0.        ]
 [-0.88015351 -0.47468915]
 [-0.68413221 -1.45528879]]
17.8355180691379 19.057286068524295
[[ 0.          0.        ]
 [-0.84897251 -0.52843701]
 [-0.64273313 -1.50693858]]
17.899283039697426 19.063386467779488
[[ 0.    

20.672839024677053 20.734036935628087
[[0.         0.        ]
 [0.96829419 0.24981266]
 [1.91949725 0.55837827]]
20.649270043537296 20.805408688582357
[[0.         0.        ]
 [0.97391254 0.22692368]
 [1.90068978 0.60253513]]
20.625362364538972 20.876111914472723
[[0.         0.        ]
 [0.97905893 0.20357706]
 [1.87698585 0.64372163]]
20.601408150755525 20.94590711800373
[[0.         0.        ]
 [0.98365411 0.18006832]
 [1.84869981 0.68176139]]
20.577698437589785 21.014537544464716
[[0.         0.        ]
 [0.98764661 0.15669773]
 [1.81625148 0.71653161]]
20.554492135706347 21.081771146292823
[[0.         0.        ]
 [0.99101673 0.13373797]
 [1.78013821 0.74797513]]
20.531988419119973 21.147439667399976
[[0.         0.        ]
 [0.99377515 0.11140444]
 [1.7408887  0.77610086]]
20.510315039666086 21.21145686704881
[[0.         0.        ]
 [0.99595608 0.08984149]
 [1.69901629 0.80097181]]
20.489532886610842 21.273814846290364
[[0.         0.        ]
 [0.99760797 0.06912547]
 [

19.104997118327276 24.805506641450126
[[ 0.          0.        ]
 [ 0.25267231 -0.96755191]
 [-0.06875328 -1.91448675]]
19.016461694515066 24.926845488938792
[[ 0.          0.        ]
 [ 0.16613192 -0.98610354]
 [-0.03831214 -1.96498179]]
18.918594665468138 25.060618312466637
[[ 0.          0.        ]
 [ 0.06898391 -0.99761777]
 [-0.00307649 -1.99501804]]
18.814774177402196 25.202213322814266
[[ 0.          0.        ]
 [-0.03477473 -0.99939518]
 [ 0.03464149 -1.99698296]]
18.71305216616682 25.340539795178564
[[ 0.          0.        ]
 [-0.13608023 -0.99069782]
 [ 0.07022609 -1.96918528]]
18.620518519763404 25.465949131269394
[[ 0.          0.        ]
 [-0.22704017 -0.97388539]
 [ 0.100036   -1.91888337]]
18.53869358638242 25.576580184171924
[[ 0.          0.        ]
 [-0.30587975 -0.95207015]
 [ 0.12352987 -1.85517999]]
18.466067021444722 25.674722897965573
[[ 0.          0.        ]
 [-0.37415822 -0.92736488]
 [ 0.14167645 -1.78405303]]
18.400733331733445 25.76315432095505
[[ 0.

17.40312314501738 28.670570431604293
[[ 0.          0.        ]
 [-0.99227682 -0.12404322]
 [-1.37822604  0.7984768 ]]
17.401075773898928 28.712375149754248
[[ 0.          0.        ]
 [-0.9925287  -0.12201141]
 [-1.41669518  0.78357282]]
17.39911420092129 28.75452982638311
[[ 0.          0.        ]
 [-0.99276612 -0.12006426]
 [-1.45471909  0.76684017]]
17.397225601813695 28.7970683212277
[[ 0.          0.        ]
 [-0.99299111 -0.11818911]
 [-1.49224238  0.74826814]]
17.39539758506614 28.840023351527744
[[ 0.          0.        ]
 [-0.9932055  -0.1163737 ]
 [-1.5292035   0.72784554]]
17.39361884174575 28.883425721813747
[[ 0.          0.        ]
 [-0.99341093 -0.11460686]
 [-1.56553378  0.70556107]]
17.391879983518255 28.927303317570644
[[ 0.          0.        ]
 [-0.99360871 -0.11287929]
 [-1.60115636  0.68140394]]
17.390174610438642 28.971679807819136
[[ 0.          0.        ]
 [-0.99379976 -0.11118465]
 [-1.63598524  0.65536464]]
17.38850065274799 29.01657299790774
[[ 0.      

19.319880423504998 30.875837696421325
[[ 0.          0.        ]
 [ 0.45317558 -0.89142128]
 [-0.06103661 -1.74908428]]
19.385455827847398 30.898972524367753
[[ 0.          0.        ]
 [ 0.51061499 -0.85980947]
 [ 0.01638052 -1.72913811]]
19.449668719766144 30.92628467212558
[[ 0.          0.        ]
 [ 0.56473557 -0.82527192]
 [ 0.0944257  -1.70777327]]
19.512378694110506 30.95780054938893
[[ 0.          0.        ]
 [ 0.61534437 -0.7882584 ]
 [ 0.17307626 -1.68514129]]
19.573442795071177 30.99348925366879
[[ 0.          0.        ]
 [ 0.66230186 -0.74923711]
 [ 0.25231716 -1.66132951]]
19.63271142087992 31.033272722671096
[[ 0.          0.        ]
 [ 0.7055192  -0.7086908 ]
 [ 0.33213554 -1.63636782]]
19.69002686429681 31.07703399813849
[[ 0.          0.        ]
 [ 0.74495737 -0.66711207]
 [ 0.41251455 -1.61023548]]
19.74522390275666 31.124624319028165
[[ 0.          0.        ]
 [ 0.78062674 -0.62499751]
 [ 0.49342692 -1.5828682 ]]
19.79813192924256 31.175869556090273
[[ 0.     

20.56210912960202 35.5112056390747
[[0.         0.        ]
 [0.98996931 0.14128259]
 [0.17441499 0.71996312]]
20.585844219808934 35.57932426477121
[[0.         0.        ]
 [0.98633743 0.1647376 ]
 [0.13328608 0.68656458]]
20.610631437894966 35.64861629014697
[[0.         0.        ]
 [0.98195147 0.18913305]
 [0.0948177  0.65064542]]
20.636493656351398 35.71914078051636
[[0.         0.        ]
 [0.97673224 0.21446242]
 [0.05928277 0.61231474]]
20.663447116316156 35.7909490103242
[[0.         0.        ]
 [0.97059767 0.24070765]
 [0.02696803 0.57171085]]
20.691498977649566 35.86408228507795
[[ 0.          0.        ]
 [ 0.96346439  0.26783645]
 [-0.00182865  0.52900563]]
20.720644544057937 35.9385694452956
[[ 0.          0.        ]
 [ 0.95525007  0.29579943]
 [-0.02680209  0.48440896]]
20.75086419690154 36.01442408319459
[[ 0.          0.        ]
 [ 0.94587633  0.32452731]
 [-0.04764505  0.43817268]]
20.78212010779882 36.09164153929084
[[ 0.          0.        ]
 [ 0.93527259  0.353

19.60135038834582 40.374575386196845
[[ 0.          0.        ]
 [ 0.68295065 -0.73046451]
 [ 1.13238239  0.16285016]]
19.548250321883046 40.39120453686534
[[ 0.          0.        ]
 [ 0.64321856 -0.76568263]
 [ 1.07773378  0.13498186]]
19.493911765073147 40.40416227297048
[[ 0.          0.        ]
 [ 0.60068357 -0.79948687]
 [ 1.02349206  0.10673219]]
19.438186156573487 40.41321745614472
[[ 0.          0.        ]
 [ 0.55522231 -0.83170198]
 [ 0.9698076   0.07830847]]
19.380935191693585 40.41811955102094
[[ 0.          0.        ]
 [ 0.5067229  -0.86210898]
 [ 0.91684228  0.04992287]]
19.32203370427125 40.41860797143192
[[ 0.          0.        ]
 [ 0.45509401 -0.8904434 ]
 [ 0.86476787  0.02178866]]
19.26137349574504 40.414423464491456
[[ 0.          0.        ]
 [ 0.4002756  -0.91639481]
 [ 0.81376312 -0.00588502]]
19.19886789267079 40.405321185081355
[[ 0.          0.        ]
 [ 0.34225141 -0.93960841]
 [ 0.76400939 -0.03289997]]
19.134456653595237 40.39108467046711
[[ 0.       

17.7589909388201 35.46071745494132
[[ 0.          0.        ]
 [-0.88688807 -0.46198436]
 [-1.67219904  0.15711714]]
17.797637021169848 35.39346093920516
[[ 0.          0.        ]
 [-0.86837642 -0.49590563]
 [-1.61030468  0.17457364]]
17.83451148688113 35.32908792102662
[[ 0.          0.        ]
 [-0.849504   -0.52758218]
 [-1.54676459  0.18923555]]
17.86992365685077 35.267173052163294
[[ 0.          0.        ]
 [-0.83029248 -0.55732791]
 [-1.48186371  0.20125954]]
17.904126600163018 35.20737733681637
[[ 0.          0.        ]
 [-0.81074833 -0.58539486]
 [-1.4158218   0.21077478]]
17.937328663240137 35.14943214260958
[[ 0.          0.        ]
 [-0.79086875 -0.6119858 ]
 [-1.34881831  0.21788907]]
17.969702806442218 35.09312717141196
[[ 0.          0.        ]
 [-0.77064528 -0.63726435]
 [-1.28100926  0.22269415]]
18.00139405481264 35.03830188006821
[[ 0.          0.        ]
 [-0.750066   -0.66136298]
 [-1.21253928  0.22527024]]
18.032525516687777 34.98483970702728
[[ 0.          

20.571582476440778 31.29919286016607
[[ 0.          0.        ]
 [ 0.98858649  0.15065443]
 [ 0.87211775 -0.84253992]]
20.581856658501692 31.226702991081158
[[ 0.          0.        ]
 [ 0.98698649  0.16080322]
 [ 0.79889013 -0.82134736]]
20.588464722837383 31.153213562007767
[[ 0.          0.        ]
 [ 0.98590235  0.16732173]
 [ 0.72620095 -0.79836724]]
20.59130210948121 31.078458356673025
[[ 0.          0.        ]
 [ 0.98542362  0.17011844]
 [ 0.65432448 -0.77347753]]
20.5902510601055 31.002201812145014
[[ 0.          0.        ]
 [ 0.98560188  0.16908262]
 [ 0.5835793  -0.74654714]]
20.585190057227045 30.924239509030745
[[ 0.          0.        ]
 [ 0.98644498  0.16409234]
 [ 0.51433125 -0.7174453 ]]
20.57600376627852 30.844400084245137
[[ 0.          0.        ]
 [ 0.98791074  0.15502377]
 [ 0.4469942  -0.6860525 ]]
20.562593320071503 30.76254809186185
[[ 0.          0.        ]
 [ 0.98990078  0.14176191]
 [ 0.38202831 -0.65227276]]
20.54488653915609 30.67858730345254
[[ 0.     

19.26814219390264 24.483691184972646
[[ 0.          0.        ]
 [ 0.40646919 -0.91366449]
 [-0.1979607  -1.71032283]]
19.29105100591052 24.384308564112615
[[ 0.          0.        ]
 [ 0.42729167 -0.90411384]
 [-0.25319945 -1.63687016]]
19.30848949436174 24.288076390920814
[[ 0.          0.        ]
 [ 0.44299228 -0.89652543]
 [-0.30475633 -1.56050736]]
19.32079847995513 24.19418333185925
[[ 0.          0.        ]
 [ 0.45399376 -0.89100486]
 [-0.35271296 -1.48195686]]
19.328226217124367 24.101968078695656
[[ 0.          0.        ]
 [ 0.46059933 -0.88760817]
 [-0.39709744 -1.40176404]]
19.330947638118545 24.01089196872341
[[ 0.          0.        ]
 [ 0.46301317 -0.8863514 ]
 [-0.43789142 -1.32036858]]
19.329082926459975 23.920516230060812
[[ 0.          0.        ]
 [ 0.46135958 -0.88721324]
 [-0.47503957 -1.23815003]]
19.322713992688968 23.830484703503743
[[ 0.          0.        ]
 [ 0.45569966 -0.8901336 ]
 [-0.50845969 -1.15545745]]
19.31189880740616 23.74051129371688
[[ 0.     

15.790979309172581 18.78056505932949
[[ 0.          0.        ]
 [-0.08292072  0.99655615]
 [-0.15185687 -0.00106493]]
15.743615850463307 18.71324275213087
[[ 0.          0.        ]
 [-0.03564503  0.99936451]
 [-0.17153645  0.00864078]]
15.696837408947502 18.646315793067213
[[ 0.          0.        ]
 [ 0.01112563  0.99993811]
 [-0.19071819  0.02052039]]
15.650657734285037 18.57983502460727
[[ 0.          0.        ]
 [ 0.05727417  0.99835849]
 [-0.20918826  0.03451318]]
15.605088829233628 18.513849624537464
[[ 0.          0.        ]
 [ 0.10269308  0.99471309]
 [-0.22674304  0.05053522]]
15.560140430037714 18.448406342716407
[[ 0.          0.        ]
 [ 0.14728507  0.98909409]
 [-0.24319185  0.06848137]]
15.515819549821456 18.383548815757592
[[ 0.          0.        ]
 [ 0.1909636   0.98159712]
 [-0.25835915  0.08822762]]
15.472130096794833 18.319316972004618
[[ 0.          0.        ]
 [ 0.23365318  0.97232001]
 [-0.27208632  0.10963376]]
15.429072575440253 18.25574653502089
[[ 0. 

13.163564818951428 14.699551946116854
[[ 0.          0.        ]
 [ 0.56232453 -0.82691664]
 [ 1.40831035 -0.29371124]]
13.144691126416111 14.62397668832884
[[ 0.          0.        ]
 [ 0.54661834 -0.83738187]
 [ 1.43044812 -0.36957324]]
13.128180229991061 14.546998902318006
[[ 0.          0.        ]
 [ 0.53271853 -0.84629248]
 [ 1.44990633 -0.44783727]]
13.114187149224884 14.46850465766812
[[ 0.          0.        ]
 [ 0.52082453 -0.85366376]
 [ 1.46643255 -0.52835548]]
13.102870936586399 14.388355737283042
[[ 0.          0.        ]
 [ 0.51113115 -0.85950274]
 [ 1.47974877 -0.61094711]]
13.09439489385827 14.306387206143231
[[ 0.          0.        ]
 [ 0.50382769 -0.86380418]
 [ 1.48954407 -0.69539038]]
13.088925874529219 14.222406173803959
[[ 0.          0.        ]
 [ 0.49909602 -0.86654669]
 [ 1.49546535 -0.78141064]]
13.086631555381405 14.136193150396693
[[ 0.          0.        ]
 [ 0.49710657 -0.86768949]
 [ 1.4971061  -0.86866328]]
13.087673672189432 14.047508561877345
[[ 0.

10.682800281315354 11.508597874882598
[[ 0.          0.        ]
 [-0.95148367  0.30769924]
 [-1.82274815 -0.18311459]]
10.626262343858368 11.53782124406903
[[ 0.          0.        ]
 [-0.93257594  0.36097385]
 [-1.78912721 -0.15508807]]
10.571798123799885 11.56426385364249
[[ 0.          0.        ]
 [-0.91154266  0.41120551]
 [-1.75415007 -0.12732282]]
10.51921615321874 11.588139800656744
[[ 0.          0.        ]
 [-0.88867077  0.4585458 ]
 [-1.71818137 -0.09994517]]
10.46833046097643 11.609669153534858
[[ 0.          0.        ]
 [-0.86419713  0.50315338]
 [-1.68149247 -0.07306562]]
10.418968342705686 11.629063990393092
[[ 0.          0.        ]
 [-0.83831785  0.54518179]
 [-1.6442845  -0.04677916]]
10.370973449445346 11.646521533708835
[[ 0.          0.        ]
 [-0.8111966   0.58477352]
 [-1.60670678 -0.0211667 ]]
10.324206215190578 11.662221515006726
[[ 0.          0.        ]
 [-0.78297138  0.62205773]
 [-1.56887066  0.0037032 ]]
10.278542925616666 11.67632586006994
[[ 0.  

7.581156978297358 11.207327787266964
[[ 0.          0.        ]
 [ 0.96301363 -0.26945269]
 [-0.01465025 -0.47962725]]
7.522858829630347 11.206971695867706
[[ 0.          0.        ]
 [ 0.94567791 -0.32510504]
 [-0.03206075 -0.53493145]]
7.464679920455007 11.210812776856866
[[ 0.          0.        ]
 [ 0.92517431 -0.37954247]
 [-0.05175117 -0.59312289]]
7.40662715684878 11.219074658118226
[[ 0.          0.        ]
 [ 0.90159466 -0.43258186]
 [-0.07353293 -0.65422614]]
7.348672034584778 11.231903787838988
[[ 0.          0.        ]
 [ 0.87502465 -0.48407837]
 [-0.09717927 -0.71821411]]
7.290750634532272 11.249369143863722
[[ 0.          0.        ]
 [ 0.84553443 -0.5339209 ]
 [-0.12243216 -0.78499995]]
7.232765828708009 11.271470933335387
[[ 0.          0.        ]
 [ 0.81317143 -0.58202425]
 [-0.1490099  -0.85443403]]
7.174590525765568 11.298157696761486
[[ 0.          0.        ]
 [ 0.77795544 -0.62831945]
 [-0.17661441 -0.92630669]]
7.116070404930634 11.329349814965804
[[ 0.       